require("nabil.options")
require("nabil.keymaps")
require("nabil.plugins-setup")

require("nabil.plugins.colorscheme")
require("nabil.plugins.alpha")
require("nabil.plugins.nvim-tree")
require("nabil.plugins.comment")
require("nabil.plugins.autopairs")
require("nabil.plugins.indent-blankline")
require("nabil.plugins.telescope")
require("nabil.plugins.lsp")
require("nabil.plugins.cmp")
require("nabil.plugins.treesitter")
require("nabil.plugins.null-ls")
require("nabil.plugins.which-key")
